# 骨幹基礎測試：世界（list＋環境）／eval 特有的／時鐘／LLM／agent。
# 跑法：jpm test 或 janet test/basic.janet
(import ../src/world :as world)
(import ../src/kernel :as kernel)
(import ../src/llm :as llm)
(import ../src/agent :as agent)

(var n 0)
(defmacro check [what form]
  ~(do (++ n) (assert ,form (string "第 " n " 條：" ,what))))

(def count-form '(do (put me :hits (inc (get me :hits))) :busy))   # 每格把自己的 :hits 加一

# ── 世界：求值、會計、路徑 ─────────────────────────────
(def w (world/make "w" count-form :hits 0))
(check "求值一格會 eval 世界的 form" (do (world/dotick w) (= (w :hits) 1)))
(check "格數會前進" (= (w :now) 1))
(check "會計記到 :busy" (= ((w :ticks) :busy) 1))
(check "path 就是身分，能用 at 找到" (= (world/at "w") w))
(def quiet (world/make "quiet" nil))
(check "沒有 form 的世界求值＝idle" (= (world/dotick quiet) :idle))
(put w :frozen true)
(check "凍住的世界不求值、只記 :frozen" (and (= (world/dotick w) :frozen) (= (w :hits) 1) (= (w :now) 1)))
(put w :frozen false)

# ── eval 特有：狀態住在環境裡、form 改寫、原語 ───────────
# 注意：要存進環境的 def 得寫在 upscope 裡；包在 do 裡只是區塊內的區域變數（見 README 的坑）
(def s1 (world/make "s1" '(upscope (def cnt 1) (next '(upscope (def cnt (+ cnt 1)) :busy)) :busy)))
(world/dotick s1)
(check "form 裡 (def x …) 存進世界自己的環境" (= (get-in s1 ['cnt :value]) 1))
(check "next 把下一格的 form 換掉了" (deep= (s1 :form) '(upscope (def cnt (+ cnt 1)) :busy)))
(world/dotick s1) (world/dotick s1)
(check "上一格 def 的東西，下一格看得到也改得動" (= (get-in s1 ['cnt :value]) 3))
(def s1b (world/make "s1b" '(do (def tmp 9) :busy)))
(world/dotick s1b)
(check "反過來：包在 do 裡的 def 只是區塊內的區域變數，不會留在環境裡" (nil? (get s1b 'tmp)))
(def s2 (world/make "s2" count-form :hits 0))
(world/dotick s2) (world/dotick s2)
(check "沒叫 next 就維持原 form，每格重跑同一句" (and (= (s2 :hits) 2) (deep= (s2 :form) count-form)))
(def p1 (world/make "p1" '(do (say (string "第 " (now) " 格")) :busy)))
(world/dotick p1)
(check "form 裡用得到 me／now／say 原語" (= ((first (p1 :outbox)) :body) "第 1 格"))
(def p2 (world/make "p2" nil))
(put p1 :form '(do (send "p2" "嗨") :busy))
(world/dotick p1)
(check "form 裡 send 用 path 找收件人" (= ((first (p2 :inbox)) :body) "嗨"))
(put p2 :form '(do (put me :got (length (mail))) :busy))
(world/dotick p2)
(check "form 裡 mail 拿得到信、拿完就清空" (and (= (p2 :got) 1) (empty? (p2 :inbox))))
(check "form 回傳三態以外的值一律算 busy" (= (world/dotick (world/make "odd" '(+ 1 1))) :busy))

# ── 小孩：kid 巢狀 list、借鐘 vs 自己的鐘 ────────────────
(def bump '(put me :hits (inc (get me :hits 0))))
(def par (world/make "par" ~(do (kid "kid" ',bump) :busy)))
(world/dotick par)
(def kid (world/at "par/kid"))
(check "小孩 path＝父 path/名字" (and kid (= (kid :path) "par/kid")))
(check "kid 第一次求值就把小孩建出來，預設借父的鐘" (= (kid :clock) :shared))
(check "這格才生的小孩，這格還不動" (nil? (kid :hits)))
(world/dotick par)
(check "借鐘的小孩跟父一起走" (= (kid :hits) 1))
(put par :form ~(do (kid "own" :own ',bump) :busy))
(world/dotick par) (world/dotick par)
(def own (world/at "par/own"))
(check "自己有鐘的小孩不跟父走" (and (= (own :clock) :own) (nil? (own :hits))))
(world/spawn kid "grandkid" nil)
(put par :form '(do (kill "par/kid") :busy))
(world/dotick par)
(check "kill 後父的 :kids 沒它" (nil? ((par :kids) "kid")))
(check "kill 連孫子一起從檔案系統消失" (and (nil? (world/at "par/kid")) (nil? (world/at "par/kid/grandkid"))))
(check "沒被 kill 的還在" (= (world/at "par/own") own))

# ── 信箱 ──────────────────────────────────────────────
(def a (world/make "a" nil)) (def b (world/make "b" nil))
(world/send a b "hi") (world/send a b {:kind :x})
(check "信進 inbox，帶寄件人 path" (and (= (length (b :inbox)) 2) (= ((first (b :inbox)) :from) "a")))
(def got (world/take-mail b |(dictionary? ($ :body))))
(check "帶條件拿信只拿符合的、其餘留著" (and (= (length got) 1) (= (length (b :inbox)) 1)))
(check "全拿就清空" (and (= (length (world/take-mail b)) 1) (empty? (b :inbox))))
(world/say a "說話")
(check "say 進 outbox" (= ((first (a :outbox)) :body) "說話"))

# ── kernel：登記、暫停、同步走格、interval ─────────────
(kernel/stop-all)
(def c1 (world/make "c1" count-form :hits 0))
(def c2 (world/make "c2" count-form :hits 0))
(kernel/register c1) (kernel/register c2 3)
(kernel/run 6 0)
(check "interval 1 的鐘 6 格走 6 次" (= (c1 :hits) 6))
(check "interval 3 的鐘 6 格走 2 次" (= (c2 :hits) 2))
(kernel/pause "c1") (kernel/run 3 0)
(check "暫停的鐘不走" (= (c1 :hits) 6))
(kernel/continue "c1") (kernel/run 1 0)
(check "繼續就走" (= (c1 :hits) 7))
(check "ls 列得出狀態與格數" (some |(= $ ["c2" :running 3]) (kernel/ls)))
(kernel/unregister "c2") (kernel/run 3 0)
(check "取消登記後不走" (= (c2 :hits) 3))
(kernel/stop-all)
(check "stop-all 清空" (empty? (kernel/ls)))

# ── LLM 世界：form 是 (llm-step)、佇列、三態、寄回結果、出錯 ──
(def L (llm/make "L" (llm/script-engine [{:text "一"} :error {:text "三"}]) 1))
(def asker (world/make "asker" nil))
(check "LLM 世界的 form 就是 (llm-step)" (deep= (L :form) '(llm-step)))
(def r1 (llm/ask L asker [{:role :user :content "?"}]))
(def r2 (llm/ask L asker [{:role :user :content "?"}]))
(check "剛送出是 pending" (= (r1 :status) :pending))
(check "沒排到的那格是 idle？不，有排隊就 busy" (= (world/dotick L) :busy))
(check "一格只做 max-per-tick 筆" (and (= (r1 :status) :done) (= (r2 :status) :pending)))
(check "結果寄回 asker 的 inbox" (= (((first (asker :inbox)) :body) :reply) {:text "一"}))
(world/dotick L)
(check "engine 丟錯 → failed，信裡有 :error" (and (= (r2 :status) :failed) (string? (((get (asker :inbox) 1) :body) :error))))
(check "沒東西時 idle" (= (world/dotick L) :idle))
(check "usage 按請求者算次數" (= ((L :usage) "asker") 2))

# ── agent：form 改寫走完一輪、等待逾時、出錯回 idle ───────
(kernel/stop-all)
(def L2 (llm/make "L2" (llm/script-engine [{:text "回一"} :error])))
(def ag (agent/make "ag" L2 :system "你是 ag"))
(def me (world/make "me" nil))
(check "agent 開場的 form 是 (agent-idle)" (= (agent/state ag) 'agent-idle))
# 旁觀者：每格看一眼 agent 的 form 換成什麼了
(def obs (world/make "obs"
  '(do (def s (first (watched :form)))
       (when (not= s (get me :last)) (put me :last s) (array/push (me :chain) s)) :busy)
  :chain @['agent-idle] :last 'agent-idle))
(put obs 'watched @{:value ag})
(kernel/register L2) (kernel/register ag) (kernel/register obs)
(world/send me ag "問一")
(kernel/run 6 0)
(check "agent 回信給寄件人" (= ((first (me :inbox)) :body) "回一"))
(check "history 是 system/user/assistant" (deep= (map |($ :role) (ag :history)) @[:system :user :assistant]))
(check "走完 form 換回 (agent-idle)" (= (agent/state ag) 'agent-idle))
(check "旁觀者看得到 form 一路改寫" (deep= (obs :chain) @['agent-idle 'agent-think 'agent-wait 'agent-act 'agent-idle]))
(kernel/unregister "obs")
(world/send me ag "問二")
(kernel/run 5 0)
(check "模型出錯：先簡單回 idle，並記下錯誤" (and (= (agent/state ag) 'agent-idle) (string? (ag :last-error))))
(kernel/pause "L2")                      # LLM 停了 → agent 等到逾時
(def ag2 (agent/make "ag2" L2 :llm-timeout 3))
(kernel/register ag2)
(world/send me ag2 "沒人回")
(kernel/run 3 0)
(check "等 LLM 時 form 是 (agent-wait …)，會計記 :wait" (and (= (agent/state ag2) 'agent-wait) (>= ((ag2 :ticks) :wait) 1)))
(check "等待的三件事就帶在那個 list 裡" (= (length (ag2 :form)) 6))
(kernel/run 3 0)
(check "逾時沒給 else → form 換回 (agent-idle)" (= (agent/state ag2) 'agent-idle))
(kernel/stop-all)

(print "proto3-1 基礎測試通過 ✓（" n " 條）")
