;;; 骨幹基礎測試（CL 版）：世界／時鐘／LLM／agent。跑法：sbcl --script test/basic.lisp
(load (merge-pathnames "../src/load.lisp" (directory-namestring *load-truename*)))
(in-package :aos)

(defvar *n* 0)
(defmacro check (what form)
  `(progn (incf *n*) (unless ,form (error "第 ~a 條：~a" *n* ,what))))

;;; ── 世界：求值、會計、路徑 ─────────────────────────────
(defvar w (make-world "w" :hits 0 :func-tick (lambda (w) (incf (gethash :hits w)) :busy)))
(check "求值一格會叫 :func-tick" (progn (dotick w) (= (w-get w :hits) 1)))
(check "格數會前進" (= (w-get w :now) 1))
(check "會計記到 :busy" (= (getf (w-get w :ticks) :busy) 1))
(check "path 就是身分，能用 world-at 找到" (eq (world-at "w") w))
(defvar quiet (make-world "quiet"))
(check "沒有 :func-tick 的世界求值＝idle" (eq (dotick quiet) :idle))
(w-put w :frozen t)
(check "凍住的世界不求值、只記 :frozen" (and (eq (dotick w) :frozen) (= (w-get w :hits) 1) (= (w-get w :now) 1)))
(w-put w :frozen nil)

;;; ── 小孩：借鐘 vs 自己的鐘 ─────────────────────────────
(defvar kid (spawn w "kid" :hits 0 :func-tick (lambda (k) (incf (gethash :hits k)))))
(defvar own (spawn w "own" :clock :own :hits 0 :func-tick (lambda (k) (incf (gethash :hits k)))))
(dotick w)
(check "小孩 path＝父 path/名字" (equal (w-get kid :path) "w/kid"))
(check "借鐘的小孩跟父一起走" (= (w-get kid :hits) 1))
(check "自己有鐘的小孩不跟父走" (= (w-get own :hits) 0))
(spawn kid "grandkid")
(kill kid)
(check "kill 後父的 :kids 沒它" (null (gethash "kid" (w-get w :kids))))
(check "kill 連孫子一起從檔案系統消失" (and (null (world-at "w/kid")) (null (world-at "w/kid/grandkid"))))
(check "沒被 kill 的還在" (eq (world-at "w/own") own))

;;; ── 信箱 ──────────────────────────────────────────────
(defvar a (make-world "a")) (defvar b (make-world "b"))
(send-mail a b "hi") (send-mail a b (list :kind :x))
(check "信進 inbox，帶寄件人 path" (and (= (length (w-get b :inbox)) 2) (equal (getf (first (w-get b :inbox)) :from) "a")))
(defvar got (take-mail b (lambda (m) (consp (getf m :body)))))
(check "帶條件拿信只拿符合的、其餘留著" (and (= (length got) 1) (= (length (w-get b :inbox)) 1)))
(check "全拿就清空" (and (= (length (take-mail b)) 1) (null (w-get b :inbox))))
(say a "說話")
(check "say 進 outbox" (equal (getf (first (w-get a :outbox)) :body) "說話"))

;;; ── kernel：登記、暫停、同步走格、interval ─────────────
(stop-all)
(defvar c1 (make-world "c1" :hits 0 :func-tick (lambda (w) (incf (gethash :hits w)))))
(defvar c2 (make-world "c2" :hits 0 :func-tick (lambda (w) (incf (gethash :hits w)))))
(register c1) (register c2 3)
(run 6 0)
(check "interval 1 的鐘 6 格走 6 次" (= (w-get c1 :hits) 6))
(check "interval 3 的鐘 6 格走 2 次" (= (w-get c2 :hits) 2))
(pause "c1") (run 3 0)
(check "暫停的鐘不走" (= (w-get c1 :hits) 6))
(resume "c1") (run 1 0)
(check "繼續就走" (= (w-get c1 :hits) 7))
(check "ls 列得出狀態與格數" (member '("c2" :running 3) (ls) :test #'equal))
(unregister "c2") (run 3 0)
(check "取消登記後不走" (= (w-get c2 :hits) 3))
(stop-all)
(check "stop-all 清空" (null (ls)))

;;; ── LLM 世界：佇列、三態、寄回結果、出錯 ───────────────
(defvar L (make-llm "L" (script-engine (list '(:text "一") :error '(:text "三"))) 1))
(defvar asker (make-world "asker"))
(defvar r1 (ask L asker '((:role :user :content "?"))))
(defvar r2 (ask L asker '((:role :user :content "?"))))
(check "剛送出是 pending" (eq (getf r1 :status) :pending))
(check "有排隊那格就 busy" (eq (dotick L) :busy))
(check "一格只做 max-per-tick 筆" (and (eq (getf r1 :status) :done) (eq (getf r2 :status) :pending)))
(check "結果寄回 asker 的 inbox" (equal (getf (getf (first (w-get asker :inbox)) :body) :reply) '(:text "一")))
(dotick L)
(check "engine 丟錯 → failed，信裡有 :error" (and (eq (getf r2 :status) :failed) (stringp (getf (getf (second (w-get asker :inbox)) :body) :error))))
(check "沒東西時 idle" (eq (dotick L) :idle))
(check "usage 按請求者算次數" (= (gethash "asker" (w-get L :usage)) 2))

;;; ── agent：一封信走完一輪、等待逾時、出錯回 idle ─────────
(stop-all)
(defvar L2 (make-llm "L2" (script-engine (list '(:text "回一") :error))))
(defvar ag (make-agent "ag" L2 :system "你是 ag"))
(defvar me (make-world "me"))
(register L2) (register ag)
(send-mail me ag "問一")
(run 5 0)
(check "agent 回信給寄件人" (equal (getf (first (w-get me :inbox)) :body) "回一"))
(check "history 是 system/user/assistant" (equal (mapcar (lambda (m) (getf m :role)) (w-get ag :history)) '(:system :user :assistant)))
(check "走完回 idle" (eq (w-get ag :state) :idle))
(send-mail me ag "問二")
(run 5 0)
(check "模型出錯：先簡單回 idle，並記下錯誤" (and (eq (w-get ag :state) :idle) (stringp (w-get ag :last-error))))
(pause "L2")                            ; LLM 停了 → agent 等到逾時
(defvar ag2 (make-agent "ag2" L2 :llm-timeout 3))
(register ag2)
(send-mail me ag2 "沒人回")
(run 3 0)
(check "等 LLM 時是 :wait，會計記 :wait" (and (eq (w-get ag2 :state) :wait) (>= (getf (w-get ag2 :ticks) :wait) 1)))
(run 3 0)
(check "逾時沒給 else → 回 idle、不再等" (and (eq (w-get ag2 :state) :idle) (null (w-get ag2 :waiting))))
(stop-all)

(format t "proto3 基礎測試（CL 版）通過 ✓（~a 條）~%" *n*)
(finish-output)
