#!/usr/bin/env python3
import pathlib,json
OUT=pathlib.Path(__file__).resolve().parent
r=json.loads((OUT/'results.json').read_text());h=json.loads((OUT/'core-history.json').read_text());cleanup=json.loads((OUT/'cleanup.json').read_text())
assert len(r['suites'])==3
lines=['# astra-6 全套與回歸抽查','', '三次全套皆 363／363，合計 1089 個測試執行，沒有失敗或本輪觀察到的不穩定案。A4-01～07、F47、§4.4 舊探針未見退化；step 450 已關回合長跑沒有錯誤。核心維持 2757／2800 總行、2123／2200 實碼，`lib/` 自 loop4 的 2757 版以來完全相同。本線沒有新 B／G。','', '| 項目 | 結果 | 證據 |','|---|---|---|']
for s in r['suites']:lines.append(f'| 全套第 {s["run"]} 次 | 363／363；實耗 {s["seconds"]:.3f} 秒；unittest {s["unittest_seconds"]:.3f} 秒；rc 0 | [suite-{s["run"]}.log](suite-{s["run"]}.log) |')
lines += ['| A4-01 | request／birth 各 EIO、EACCES、ESTALE，6／6 注入命中；留請求、不給回條、birth 不變、task 活；復原可掛上 | [core/results.json](core/results.json) |', '| A4-02／06 | 同 req_id 競爭只起一次；birth 換代後相同 req_id 可重新排入，符合去重期 | [core/results.json](core/results.json) |','| A4-05 | 真 daemon 動態登記 nested node 後，既有 audit 包裝器正確標越界寫 bad，自己的寫入 ok | [core/results.json](core/results.json) |','| A4-03／04／07 | 初始 wait 耐性正確；壞型別回 JSON 診斷、wake 合法；timeout kill 帶 run | [step/step-probes.json](step/step-probes.json) |','| §4.4(a)／(b) | after-birth、before-once-delete 真 SIGKILL 仍最多一次；一般及同回合重播都在報結束下一個 tock 才刪槽 | [core/results.json](core/results.json) |','| F47 核心／模組 | 同回合重播補通知；跨回合不補；history gap、once_retry 漏取樣／pending 符合契約 | [core/results.json](core/results.json) |','| F47 step | 4 次 EIO 漏通知、槽已清仍接原 request／attempt，a／b 各一次；漏 3 回合通知後耐性不重設 | [step/f47-step.json](step/f47-step.json) |','| 核心行數／歷史 | 單跑 test_budget rc 0；9 支 aos7 核心 2757／2123；lib 全 18 檔 SHA256 與 daf8d5cf 相同，之後 git history／diff 皆空 | [core-budget.log](core-budget.log)、[core-lines.json](core-lines.json)、[core-history.json](core-history.json) |','', '共核心 17 案、step 8 案、F47 step 2 案。SIGKILL／漏通知後保守停住列 X；刻意刪 frame.pc 列 M，不是 bug。原探針部分情境主要記錄觀察，本輪另於 [summarize.py](summarize.py) 對 entered wait、延遲 intent、預設最多重送一次、active close 拒收補做結果斷言。','', '## adapt flaky 留意','', 'adapt 的 28 案在三次全套皆通過（84 次）；包含 20／200 ms、200／20 ms、50／50 ms、pause／SIGKILL／重建、300 回合檔數與 `test_daemon_kill9_restart`。完整逐案結果見 [results.json](results.json)。三次通過只是本輪沒有觀察到 flaky，不是保證任何負載都穩定。','', '版本紀錄只有 d3738e04 初次加入整份 adapt 測試，現有測試註解和 repo 證據未指出「放寬前」斷言，不能確認使用者提及的確切歷史變更。現行 `test_daemon_kill9_restart` 用 `regs[0].my_round >= before.my_round`，允許觀察之間多走回合；仍查不 reset、不 void、since 不變、最後接到更新來源回合。此項是候選對照，不冒稱已定位原放寬案。','', '## step 450 已關回合長跑','', 'CSV convert→stats→end，restart_on_end=true、interval 20 ms，真 daemon。退出前另讀 `round.json` 確認 round=450、open=false。','', '| 指標 | 本輪 |','|---|---:|']
l=r['longrun'];lines += [f'| 已關回合／實耗 | {l["closed_round"]}／{l["seconds"]:.3f} 秒 |',f'| 回合樣本／完成快照 | {l["samples"]}／{l["completed_snapshots"]} |',f'| report rows=5、convert request 正確、每步 attempt=1 | {l["completed_snapshots"]}／{l["completed_snapshots"]} |','| halt／error | 0 |','| 同 ended 階段 job 檔數 | 固定 10 |','| 同 ended 階段 job bytes | 4381～4397 |','| 全階段 job／node／root 檔數 | 4～10／7～32／8～39 |','', '同階段檔數沒有隨完成工作累積；bytes 微幅差異來自識別與回合文字長度。不宣稱任意故障路徑或無限長跑皆有界。[完整長跑 JSON](step/longrun.json)、[打包快照](longrun-snapshots.tar.gz)。','', '## 重跑與清場','', '從 repo 根，依序執行：','', '```sh','PYTHONDONTWRITEBYTECODE=1 python3 proto7-2/notes/play/2026-10-04-astra-6-infra-evidence/regression/run_suites.py','PYTHONDONTWRITEBYTECODE=1 python3 proto7-2/notes/play/2026-10-04-astra-6-infra-evidence/regression/run_probes.py','PYTHONDONTWRITEBYTECODE=1 python3 proto7-2/notes/play/2026-10-04-astra-6-infra-evidence/regression/check_core.py','PYTHONDONTWRITEBYTECODE=1 python3 proto7-2/notes/play/2026-10-04-astra-6-infra-evidence/regression/summarize.py','PYTHONDONTWRITEBYTECODE=1 python3 proto7-2/notes/play/2026-10-04-astra-6-infra-evidence/regression/final_cleanup.py','PYTHONDONTWRITEBYTECODE=1 python3 proto7-2/notes/play/2026-10-04-astra-6-infra-evidence/regression/write_summary.py','```','', '探針由 astra-5 複製，僅換本輪證據／暫存目錄名稱；產品、測試與舊證據不改。全套實際入口為 `python3 proto7-2/tests/run_all.py -v`，三次循序；wrapper 保存 UTC 起訖、PID、總耗時。`suite-*-cases.json` 的耗時僅涵蓋沒有額外 docstring 行的 145 案，屬輸出觀察值；完整 363 案的 pass/fail 以逐項 log 為準。','', f'全套與探針全部使用自己新建 /tmp 根，既有 per-case cleanup 按 PID／PGID 收自己的程序。最終檢查 {len(cleanup["roots"])} 個已知根、{len(cleanup["known_pids"])} 個已知入口 PID，路徑皆不存在、AOS7_ROOT／cmdline 相符程序為零，並保存 ps。[cleanup.json](cleanup.json)、[ps-final.txt](ps-final.txt)。未碰 scratchpad；未 commit／push；未使用 LLM。','', '最該修的三條：沒有。','']
(OUT/'summary.md').write_text('\n'.join(lines))
