;;; 骨幹基礎測試（CL 版）：世界／時鐘／LLM／agent，加上 eval 版特有的那幾條。
;;; 跑法：sbcl --script test/basic.lisp
(load (merge-pathnames "../src/load.lisp" (directory-namestring *load-truename*)))
(in-package :aos)

(defvar *n* 0)
(defmacro check (what form)
  `(progn (incf *n*) (unless ,form (error "第 ~a 條：~a" *n* ,what))))

(defun bump () (setvar 'hits (1+ (var 'hits 0))) :busy)   ; 測試用的一句 list

;;; ── 世界：求值、會計、路徑 ─────────────────────────────
(defvar w (make-world "w" '(bump)))
(check "求值一格會 eval :form" (progn (dotick w) (= (w-get w 'hits) 1)))
(check "格數會前進" (= (w-get w :now) 1))
(check "會計記到 :busy" (= (getf (w-get w :ticks) :busy) 1))
(check "path 就是身分，能用 world-at 找到" (eq (world-at "w") w))
(defvar quiet (make-world "quiet" nil))
(check "沒有 form 的世界求值＝idle" (eq (dotick quiet) :idle))
(w-put w :frozen t)
(check "凍住的世界不求值、只記 :frozen" (and (eq (dotick w) :frozen) (= (w-get w 'hits) 1) (= (w-get w :now) 1)))
(w-put w :frozen nil)

;;; ── 小孩：借鐘 vs 自己的鐘 ─────────────────────────────
(defvar kid1 (with-world w (kid "kid" '(bump))))
(defvar own1 (with-world w (kid "own" :own '(bump))))
(dotick w)
(check "小孩 path＝父 path/名字" (equal (w-get kid1 :path) "w/kid"))
(check "借鐘的小孩跟父一起走" (= (w-get kid1 'hits) 1))
(check "自己有鐘的小孩不跟父走" (= (w-get own1 'hits 0) 0))
(with-world kid1 (kid "grandkid" nil))
(kill "w/kid")
(check "kill 後父的 :kids 沒它" (null (gethash "kid" (w-get w :kids))))
(check "kill 連孫子一起從檔案系統消失" (and (null (world-at "w/kid")) (null (world-at "w/kid/grandkid"))))
(check "沒被 kill 的還在" (eq (world-at "w/own") own1))

;;; ── 信箱 ──────────────────────────────────────────────
(defvar a (make-world "a" nil)) (defvar b (make-world "b" nil))
(with-world a (send "b" "hi") (send "b" (list :kind :x)))
(check "信進 inbox，帶寄件人 path" (and (= (length (w-get b :inbox)) 2) (equal (getf (first (w-get b :inbox)) :from) "a")))
(defvar got (with-world b (mail (lambda (m) (consp (getf m :body))))))
(check "帶條件拿信只拿符合的、其餘留著" (and (= (length got) 1) (= (length (w-get b :inbox)) 1)))
(check "全拿就清空" (and (= (length (with-world b (mail))) 1) (null (w-get b :inbox))))
(with-world a (say "說話"))
(check "say 進 outbox" (equal (getf (first (w-get a :outbox)) :body) "說話"))

;;; ── kernel：登記、暫停、同步走格、interval ─────────────
(stop-all)
(defvar c1 (make-world "c1" '(bump)))
(defvar c2 (make-world "c2" '(bump)))
(register c1) (register c2 3)
(run 6 0)
(check "interval 1 的鐘 6 格走 6 次" (= (w-get c1 'hits) 6))
(check "interval 3 的鐘 6 格走 2 次" (= (w-get c2 'hits) 2))
(pause "c1") (run 3 0)
(check "暫停的鐘不走" (= (w-get c1 'hits) 6))
(resume "c1") (run 1 0)
(check "繼續就走" (= (w-get c1 'hits) 7))
(check "ls 列得出狀態與格數" (member '("c2" :running 3) (ls) :test #'equal))
(unregister "c2") (run 3 0)
(check "取消登記後不走" (= (w-get c2 'hits) 3))
(stop-all)
(check "stop-all 清空" (null (ls)))

;;; ── LLM 世界：佇列、三態、寄回結果、出錯 ───────────────
(defvar L (make-llm "L" (script-engine (list '(:text "一") :error '(:text "三"))) 1))
(defvar asker (make-world "asker" nil))
(defvar r1 (ask L asker '((:role :user :content "?"))))
(defvar r2 (ask L asker '((:role :user :content "?"))))
(check "剛送出是 pending" (eq (getf r1 :status) :pending))
(check "有排隊那格就 busy" (eq (dotick L) :busy))
(check "一格只做 max-per-tick 筆" (and (eq (getf r1 :status) :done) (eq (getf r2 :status) :pending)))
(check "結果寄回 asker 的 inbox" (equal (getf (getf (first (w-get asker :inbox)) :body) :reply) '(:text "一")))
(dotick L)
(check "engine 丟錯 → failed，信裡有 :error" (and (eq (getf r2 :status) :failed) (stringp (getf (getf (second (w-get asker :inbox)) :body) :error))))
(check "沒東西時 idle" (eq (dotick L) :idle))
(check "usage 按請求者算次數" (= (gethash "asker" (w-get L :usage)) 2))

;;; ── agent：一封信走完一輪、等待逾時、出錯回 idle ─────────
(stop-all)
(defvar L2 (make-llm "L2" (script-engine (list '(:text "回一") :error))))
(defvar ag (make-agent "ag" L2 :system "你是 ag"))
(defvar me1 (make-world "me1" nil))
(register L2) (register ag)
(with-world me1 (send "ag" "問一"))
(run 5 0)
(check "agent 回信給寄件人" (equal (getf (first (w-get me1 :inbox)) :body) "回一"))
(check "history 是 system/user/assistant" (equal (mapcar (lambda (m) (getf m :role)) (w-get ag 'history)) '(:system :user :assistant)))
(check "走完回 (agent-idle)" (eq (state-of ag) 'agent-idle))
(with-world me1 (send "ag" "問二"))
(run 5 0)
(check "模型出錯：先簡單回 idle，並記下錯誤" (and (eq (state-of ag) 'agent-idle) (stringp (w-get ag 'last-error))))
(pause "L2")                            ; LLM 停了 → agent 等到逾時
(defvar ag2 (make-agent "ag2" L2 :llm-timeout 3))
(register ag2)
(with-world me1 (send "ag2" "沒人回"))
(run 3 0)
(check "等 LLM 時是 (agent-wait …)，會計記 :wait" (and (eq (state-of ag2) 'agent-wait) (>= (getf (w-get ag2 :ticks) :wait) 1)))
(run 3 0)
(check "逾時 → 回 (agent-idle)、不再等" (equal (w-get ag2 :form) '(agent-idle)))
(stop-all)

;;; ── eval 版特有的 ─────────────────────────────────────
(defun accum () (setvar 'acc (cons (now) (var 'acc))) :busy)
(defvar sw (make-world "sw" '(accum)))
(dotick sw) (dotick sw) (dotick sw)
(check "setvar 寫的狀態跨格留在環境裡" (equal (w-get sw 'acc) '(3 2 1)))

(defun step-a () (setvar 'log (append (var 'log) (list :a))) (next '(step-b)) :busy)
(defun step-b () (setvar 'log (append (var 'log) (list :b))) :busy)
(defvar nw (make-world "nw" '(step-a)))
(dotick nw)
(check "next 把 :form 換掉了" (equal (w-get nw :form) '(step-b)))
(dotick nw) (dotick nw)
(check "下一格跑新的 form；沒叫 next 就每格重跑同一句" (equal (w-get nw 'log) '(:a :b :b)))

(defvar pw (make-world "pw" '(kid "k" '(bump))))
(dotick pw)
(check "kid 巢狀 list：第一次求值就建立" (and (world-at "pw/k") (equal (w-get (world-at "pw/k") :path) "pw/k")))
(check "那一格才生的小孩還沒跟著走" (= (w-get (world-at "pw/k") :now) 0))
(dotick pw)
(check "之後每格跟著父走一格" (= (w-get (world-at "pw/k") :now) 1))

(defvar agw (make-agent "agw" L2 :llm-timeout 7))
(register agw) (with-world me1 (send "agw" "等等")) (run 2 0) (stop-all)  ; 停在等待那一格
(check "等待的 form 把『等什麼／等到了叫誰／幾格放棄』當資料帶在身上"
       (let ((f (w-get agw :form)))
         (and (eq (first f) 'agent-wait)
              (eq (first (second (second f))) :llm-result)
              (eq (second (third f)) 'agent-got-llm)
              (= (fourth f) 7))))

(defun record-state (path)
  (let ((s (state-of (world-at path))))
    (unless (eq s (var 'last))
      (setvar 'last s)
      (setvar 'seq (append (var 'seq) (list s)))))
  :busy)
(defvar L3 (make-llm "L3" (script-engine (list '(:text "嗨")))))
(defvar ag3 (make-agent "ag3" L3))
(defvar obs (make-world "obs" '(record-state "ag3")))
(defvar me3 (make-world "me3" nil))
(register obs) (register L3) (register ag3)
(with-world me3 (send "ag3" "哈囉"))
(run 6 0)
(check "旁觀者看得到 form 一路 idle → think → wait → act → idle"
       (equal (w-get obs 'seq) '(agent-idle agent-think agent-wait agent-act agent-idle)))
(stop-all)
(format t "proto3-1 基礎測試（CL 版）通過 ✓（~a 條）~%" *n*)
(finish-output)
