# 骨幹基礎測試：世界／時鐘／LLM／agent。跑法：jpm test 或 janet test/basic.janet
(import ../src/world :as world)
(import ../src/kernel :as kernel)
(import ../src/llm :as llm)
(import ../src/agent :as agent)

(var n 0)
(defmacro check [what form]
  ~(do (++ n) (assert ,form (string "第 " n " 條：" ,what))))

# ── 世界：求值、會計、路徑 ─────────────────────────────
(def w (world/make "w" :hits 0 :func-tick (fn [w] (update w :hits inc) :busy)))
(check "求值一格會叫 :func-tick" (do (world/dotick w) (= (w :hits) 1)))
(check "格數會前進" (= (w :now) 1))
(check "會計記到 :busy" (= ((w :ticks) :busy) 1))
(check "path 就是身分，能用 at 找到" (= (world/at "w") w))
(def quiet (world/make "quiet"))
(check "沒有 :func-tick 的世界求值＝idle" (= (world/dotick quiet) :idle))
(put w :frozen true)
(check "凍住的世界不求值、只記 :frozen" (and (= (world/dotick w) :frozen) (= (w :hits) 1) (= (w :now) 1)))
(put w :frozen false)

# ── 小孩：借鐘 vs 自己的鐘 ─────────────────────────────
(def kid (world/spawn w "kid" :hits 0 :func-tick (fn [k] (update k :hits inc))))
(def own (world/spawn w "own" :clock :own :hits 0 :func-tick (fn [k] (update k :hits inc))))
(world/dotick w)
(check "小孩 path＝父 path/名字" (= (kid :path) "w/kid"))
(check "借鐘的小孩跟父一起走" (= (kid :hits) 1))
(check "自己有鐘的小孩不跟父走" (= (own :hits) 0))
(world/spawn kid "grandkid")
(world/kill kid)
(check "kill 後父的 :kids 沒它" (nil? ((w :kids) "kid")))
(check "kill 連孫子一起從檔案系統消失" (and (nil? (world/at "w/kid")) (nil? (world/at "w/kid/grandkid"))))
(check "沒被 kill 的還在" (= (world/at "w/own") own))

# ── 信箱 ──────────────────────────────────────────────
(def a (world/make "a")) (def b (world/make "b"))
(world/send a b "hi") (world/send a b {:kind :x})
(check "信進 inbox，帶寄件人 path" (and (= (length (b :inbox)) 2) (= ((first (b :inbox)) :from) "a")))
(def got (world/take-mail b |(dictionary? ($ :body))))
(check "帶條件拿信只拿符合的、其餘留著" (and (= (length got) 1) (= (length (b :inbox)) 1)))
(check "全拿就清空" (and (= (length (world/take-mail b)) 1) (empty? (b :inbox))))
(world/say a "說話")
(check "say 進 outbox" (= ((first (a :outbox)) :body) "說話"))

# ── kernel：登記、暫停、同步走格、interval ─────────────
(kernel/stop-all)
(def c1 (world/make "c1" :hits 0 :func-tick (fn [w] (update w :hits inc))))
(def c2 (world/make "c2" :hits 0 :func-tick (fn [w] (update w :hits inc))))
(kernel/register c1) (kernel/register c2 3)
(kernel/run 6 0)
(check "interval 1 的鐘 6 格走 6 次" (= (c1 :hits) 6))
(check "interval 3 的鐘 6 格走 2 次" (= (c2 :hits) 2))
(kernel/pause "c1") (kernel/run 3 0)
(check "暫停的鐘不走" (= (c1 :hits) 6))
(kernel/continue "c1") (kernel/run 1 0)
(check "繼續就走" (= (c1 :hits) 7))
(check "ls 列得出狀態與格數" (some |(= $ ["c2" :running 3]) (kernel/ls)))
(kernel/unregister "c2") (kernel/run 3 0)
(check "取消登記後不走" (= (c2 :hits) 3))
(kernel/stop-all)
(check "stop-all 清空" (empty? (kernel/ls)))

# ── LLM 世界：佇列、三態、寄回結果、出錯 ───────────────
(def L (llm/make "L" (llm/script-engine [{:text "一"} :error {:text "三"}]) 1))
(def asker (world/make "asker"))
(def r1 (llm/ask L asker [{:role :user :content "?"}]))
(def r2 (llm/ask L asker [{:role :user :content "?"}]))
(check "剛送出是 pending" (= (r1 :status) :pending))
(check "沒排到的那格是 idle？不，有排隊就 busy" (= (world/dotick L) :busy))
(check "一格只做 max-per-tick 筆" (and (= (r1 :status) :done) (= (r2 :status) :pending)))
(check "結果寄回 asker 的 inbox" (= (((first (asker :inbox)) :body) :reply) {:text "一"}))
(world/dotick L)
(check "engine 丟錯 → failed，信裡有 :error" (and (= (r2 :status) :failed) (string? (((get (asker :inbox) 1) :body) :error))))
(check "沒東西時 idle" (= (world/dotick L) :idle))
(check "usage 按請求者算次數" (= ((L :usage) "asker") 2))

# ── agent：一封信走完一輪、等待逾時、出錯回 idle ─────────
(kernel/stop-all)
(def L2 (llm/make "L2" (llm/script-engine [{:text "回一"} :error])))
(def ag (agent/make "ag" L2 :system "你是 ag"))
(def me (world/make "me"))
(kernel/register L2) (kernel/register ag)
(world/send me ag "問一")
(kernel/run 5 0)
(check "agent 回信給寄件人" (= ((first (me :inbox)) :body) "回一"))
(check "history 是 system/user/assistant" (deep= (map |($ :role) (ag :history)) @[:system :user :assistant]))
(check "走完回 idle" (= (ag :state) :idle))
(world/send me ag "問二")
(kernel/run 5 0)
(check "模型出錯：先簡單回 idle，並記下錯誤" (and (= (ag :state) :idle) (string? (ag :last-error))))
(kernel/pause "L2")                      # LLM 停了 → agent 等到逾時
(def ag2 (agent/make "ag2" L2 :llm-timeout 3))
(kernel/register ag2)
(world/send me ag2 "沒人回")
(kernel/run 3 0)
(check "等 LLM 時是 :wait，會計記 :wait" (and (= (ag2 :state) :wait) (>= ((ag2 :ticks) :wait) 1)))
(kernel/run 3 0)
(check "逾時沒給 else → 回 idle、不再等" (and (= (ag2 :state) :idle) (nil? (ag2 :waiting))))
(kernel/stop-all)

(print "proto3 基礎測試通過 ✓（" n " 條）")
